/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projet;

import java.awt.*;
import java.awt.Toolkit;

/**
 *
 * @author dongm
 */
public class FrameEmprunt extends javax.swing.JFrame {

    /**
     * Creates new form FrameBook
     */
    public FrameEmprunt() {
        this.setVisible(true);
        Image icon = Toolkit.getDefaultToolkit().getImage("C:/Users/dongm/OneDrive/Bureau/design/logo1.png");
        this.setIconImage(icon); 
        this.setTitle("L I B R A R Y");
        this.setSize(1005,580);
        this.setResizable(false);
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        JPanelEmprunt b=new JPanelEmprunt(this);
        b.setBounds(0,0,1005,560);
        this.add(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(230, 231, 228));
        setResizable(false);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
